### ISSUE TITLE
Strange behaviour when opening Atom from a Bunch

### ISSUE THREAD

**Issue by dotjay** [ttscoff/bunch#124]
I noticed a strange issue when opening the Atom text editor. If I open Atom using its app icon, it opens with one new window, ready to open a project. When I include it in a Bunch using the name "Atom", it opens two windows every time the app opens.

I've had [similar issues with Atom](https://github.com/atom/atom/issues/10044) before, so I've tried the usual things, including clearing Atom's window state and disabling all community packages in Atom.

It ordinarily would only be a minor inconvenience, but it does slow down the time taken for Atom to render and I need to add several seconds' pause before sending the application some key commands to open the project I want to work on. The only other way I've been able to get around this issue is to keep Atom open all the time.

I opened up the log and only found this error sometimes, which may be unrelated, but I tried a variation on the process name anyway, but that wouldn't work at all:

```
2021-07-26 12:59:09: 🔴Application Atom failed to launch (Error Domain=NSCocoaErrorDomain Code=256 "The application “Atom.app” could not be launched because a miscellaneous error occurred." UserInfo={NSURL=file:///Applications/Atom.app/, NSLocalizedDescription=The application “Atom.app” could not be launched because a miscellaneous error occurred., NSUnderlyingError=0x600000c9d8f0 {Error Domain=NSOSStatusErrorDomain Code=-600 "procNotFound: no eligible process with specified descriptor" UserInfo={_LSLine=379, _LSFunction=_LSAnnotateAndSendAppleEventWithOptions}}})
```

I wonder if there's something about the way that apps are called by Bunch?

**Comment by ttscoff** [comment]
Atom is an Electron app, which leads to all kinds of weirdness. You could test out other methods of opening/closing the app to see if you had better results:

1. I assume Atom has a CLI you could call with `$ /usr/local/bin/atom` or whatever.
2. You could see if it responds differently when triggered by AppleScript `* tell app "Atom" to launch`

(If you use either of those and still want Atom to close when the Bunch does, you'll need accompanying `!$` or `!*` lines to run the opposite scripts when closing.

You could also try using the bundle identifier instead of the name, though I'm not sure that would make any difference in the way Atom launches and how it handles new instances. 

Does "Atom" appear more than once in the Bunch, or is the Bunch opening multiple files in it? Atom may interpret activation calls as new processes, causing it to basically launch two instances of itself instead of activating the first one. I know VS Code has some issues in that area.
