### ISSUE TITLE
Localisation issue using macOS default apps (Preview, Messages etc)

### ISSUE THREAD

**Issue by feekApp** [ttscoff/bunch#153]
Hi Brett,

My default system language is Dutch. So some default macOS Apps are translated:
- Preview => Voorvertoning
- Messages => Berichten

When adding these apps in a Bunch the Apps are opened as expected, but after closing the Bunch the Apps are not closed:
2021-10-15 08:37:50: 🔴App not running (Messagess)
2021-10-15 08:37:50: 🔴App not running (Preview)

I expect that there is a Localisation issue. Only Apps that have a translation, does not close after closing the Bunch.

When adding the translated App names in the Bunch (Voorvertoning, Berichten), the Apps are also opened on starting a Bunch, but also not closing:
2021-10-15 08:43:12: 🔴App not running (Berichten)
2021-10-15 08:43:12: 🔴App not running (Voorvertoning)

When adding a file to open in Preview (translated):
```
Voorvertoning
- ~/Documents/test.pdf
```

The following error occurs:

2021-10-15 08:44:38: 🔴Application failed to launch (Voorvertoning) and/or open file (~/Documents/test.pdf)

**Comment by ttscoff** [comment]
This is going to be a bit of a tough one to debug. I'll have to install 
Dutch to replicate. I have some guesses, but will have to test.

In the meantime, you might have better luck using bundle identifiers. 
Instead of "Preview" and "Messages", try:

com.apple.Preview
com.apple.MobileSMS

Let me know if that works for you.

However, your issue with opening a file in Preview doesn't seem to be 
related. In testing, I can't get Preview to open _any_ files at all. Not 
sure what's going on there and will have to look into it. As a stopgap, 
check out the Bunch `display` command, which can load a preview of any 
file type that has a Quick Look plugin. It's probably not what you need, 
but just in case: https://bunchapp.co/docs/bunch-files/commands/display/

-Brett

**Comment by Younghart** [comment]
I'd like to chime in on this irregularity with further details from the German perspective. 
**1. App Names**
Some apps get launched and quit by their localized names (Kalender/Calendar, Karten/Maps), some need the English original app name (Kontakte/Contacts, Nachrichten/Messages). right now I'll help myself by using the "Get Info" dialogue in the Finder on an app to find out its official name.
**2. Folder Names**
Some Default sub-folders of the home folder (Pictures, Documents, Movies, Music, Desktop, Public) have localized versions (Bilder, Dokumente, Filme, Musik, Schreibtisch, Öffentlich) that can be used throughout the Finder sphere, e.g. by clicking around, searching via Spotlight, or with the "Go to" command.. I can't use these localized folder names within Bunch documents and must remember to use the proper folder names. (Current workaround: I drag the folder whose path I want to use onto a Terminal window, copy the resulting path into bunch, then remove the backslashes before the spaces).

It would be great if Bunch could somehow tap into the database of localized aliases of apps and folder names (that I assume exists somewhere within macOS) and parse them correctly.

**Comment by ttscoff** [comment]
@Younghart There's not a way to take a plain text string (path) and know that it needs translation. I would have to build my own dictionary of every possible permutation/localization of all of the system directories for every language and test every path in every Bunch provided against it. I have to take the string as an actual path. The easiest way to get the actual path to a file should be right clicking it in Finder, pressing Option while the menu is showing, and selecting Copy as Pathname.

@feekApp I'll have to see what happens if I attempt to have Bunch grab a bundle id for a Dutch app name. Might need to send you a test build to see what you get. Will keep you posted, but I'd just use the bundle ids for now.

**Comment by Younghart** [comment]
Thank you for taking the time to answer – and for the workaround via "copy as path name" (in german "[…] als Pfadname kopieren"). This already saves a lot of work.
