### ISSUE TITLE
Visual Studio Code can't be opened - Issue with command

### ISSUE THREAD

**Issue by shieldcy** [ttscoff/bunch#208]
Hello,

I am facing an issue with Visual Studio.
I have this command:
Finder
- ~/Documents/project.code-workspace

It was working fine but since 2-3 weeks ago I am getting this error whenever I run the bunch
**Error Message**: "The application “Visual Studio Code.app” can’t be opened. - 1703"

Can anyone please suggest a way to open a VisualStudio workspace file? I am not sure what was changed exactly and why the bunch command stopped working

Thank you

**Comment by ttscoff** [comment]
Does double clicking that file in finder successfully open VS Code?

-Brett
________________________________
From: SS_cy ***@***.***>
Sent: Wednesday, March 30, 2022 6:46:29 AM
To: ttscoff/bunch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ttscoff/bunch] Visual Studio Code can't be opened - Issue with command (Issue #208)


Hello,

I am facing an issue with Visual Studio.
I have this command:
Finder

  *   ~/Documents/flathero.code-workspace

It was working fine but since 2-3 weeks ago I am getting this error whenever I run the bunch
Error Message: "The application “Visual Studio Code.app” can’t be opened. - 1703"

Can anyone please suggest a way to open a VisualStudio workspace file? I am not sure what was changed exactly and why the bunch command stopped working

Thank you

**Comment by shieldcy** [comment]
Yes, the file opens successfully when I do it manually.
It was also working fine with Bunch.

I am on a Mac, Monterey Version 12.3
Visual Studio Code Version: 1.65.2
Bunch Version 1.4.7 (139)
