### ISSUE TITLE
Add "New Bunch With Open Apps" to AppleScript

### ISSUE THREAD

**Issue by stevelw** [ttscoff/bunch#222]
Currently the only way to trigger "New Bunch With Open Apps" is via the menubar using the mouse (or an overly complicated AppleScript UI command). It would be useful to be able to trigger this via a Bunch AppleScript command. 

Use case: Add Bunch as a "Hook to new" option in Hook. When setting up a new work project you could trigger Hook to New from the project task list and create a new Bunch with the project relevant Bunch actions.

**Comment by ttscoff** [comment]
You could always just send the keyboard shortcut to open the Bunch menu 
and then ⇧⌘N instead of UI scripting, but I take your point.

There's no "bunch" object in the applescript library, only direct 
commands, so the syntax would get a little unusual. It would have to be 
something awkward like

```
tell app "Bunch" to create new bunch with open apps named "New Bunch"
```

That would just immediately save the new Bunch to the bunch folder with 
the filename "New Bunch.bunch". Is that what you're thinking?

**Comment by ttscoff** [comment]
I added this in the current beta: <https://bunchapp.co/docs/integration/applescript/#runningapps>
