### ISSUE TITLE
Recents Finder Window Opens

### ISSUE THREAD

**Issue by nickwild-999** [ttscoff/bunch#304]
I have a simple Bunch
```
---
Title: Test
---

@@
(hide desktop)

Finder
- XX
- 
```

However when I run it it systematically opens a Recents Finder window even if this has not previous been open.

EDIT: Now it has an additional issues - it is also not hiding Arc when it runs. It flashes briefly, but then nothing. I am using Spaces, I presume this is not relevent

Nothing is being reported as out of the ordinary in the logs

Any ideas anyone?

**Comment by ttscoff** [comment]
Finder will always open one window to your default view whenever it's 
activated and no windows are open. The (desktop) commands both restart 
Finder, which activates it, and the XX command you're sending will still 
activate and open a new window, even if it closes the others. I believe 
you should be able to work around this with a little AppleScript, but 
I'd have to play with it.


Try adding this instead of the Finder/XX command:

```
* tell application "Finder" to close every window
```

Let me know if that helps.

-Brett

**Comment by nickwild-999** [comment]
Thanks @ttscoff This works perfectly
