### ISSUE TITLE
Xcode Windows

### ISSUE THREAD

**Issue by maxoriggi** [ttscoff/bunch#31]
I have created a few bunches to launch Xcode with different projects. 
I use the XX command to close current windows and then add the project file. 
The issue I have is that the project opens with the default Xcode window layout and not the one I last set. 
Just to check that Xcode isn't having its own problems, I can close and reopen projects manually and the layout is persisted correctly.

**Comment by ttscoff** [comment]
First, what version of Bunch is this with?

**Comment by maxoriggi** [comment]
The latest one b72.

**Comment by ttscoff** [comment]
I think this might be happening because Bunch closes ALL windows when you use `XX`, and Xcode treats tabs as windows (hitting ⌘W closes a tab, not the whole window). I'm not sure this is something I want to work around on a case by case basis, and it's difficult to find a way to close all windows that works universally. Every app has different shortcuts for closing a window full of tabs. In the case of Xcode, you might consider sending keystrokes (`- {^~@w}` would close the frontmost project), which would work if you only ever had one project to close. You could send it multiple times, but you'd probably get an error beep once no more projects were open. 

The more elegant but complex option would be to write a custom AppleScript that looped through the windows and closed the project, though I'm not sure that's any more feasible than what Bunch already tries to do...

**Comment by maxoriggi** [comment]
I see, I'll try the keystrokes solution, it should work fine for my needs.

**Comment by maxoriggi** [comment]
Had to try different solutions, Xcode is somewhat picky (buggy?), but using the shift command w shortcut with some pause around it works reliably so far.

**Comment by ttscoff** [comment]
I've been considering adding a shorthand for pauses in key combo strings. Haven't quite figured out either the logistics or the syntax yet, but I've run into a few instances where pausing between keystrokes would be a lot easier if I could just add a couple characters in the `- {}` command. Working on that...

**Comment by maxoriggi** [comment]
👍, while the pause command works fine, a more compact syntax would be definitely welcomed.
