### ISSUE TITLE
Bunch CLI does not recognize subfolders

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#49]
When I list the bunches via the CLI, bunches in the subfolder do not load.

![bunch folders](https://user-images.githubusercontent.com/8632637/114209889-fe9c0c00-9913-11eb-8385-15a23e029fb8.png)

**Comment by ttscoff** [comment]
Ok, so this is fixed, buuuuut... The fix depends on some new features in the Beta that aren't in the stable release yet. Which I guess is kind of the point because the stable release doesn't support subfolders anyway. However, I'm using `osascript` to call built-in AppleScript functions instead of using `defaults read` (it's way faster, and won't suffer from the caching issues that defaults does), but that means I have to use `tell app "Bunch Beta"`. Which means that if I hardcode that into the CLI, it'll stop working for people not on the beta yet, so I'm going to hold off on pushing the fix until the beta switches back to the main channel.

If you want to get the jump on it, I have committed the changes to the [CLI repo](https://github.com/ttscoff/bunchcli). If you pull that, you can run `bundle install` and `rake package` to build the gem, then use `gem install pkg/xxx.gem` to install it.

**Comment by ttscoff** [comment]
Pushed the gem as a pre-release. You can install using `gem install bunchcli --pre`. Let me know if it works for you.
