### ISSUE TITLE
setting variables in embedded snippets

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#56]
I have [this bunch](https://gist.github.com/kjaymiller/1e20977ced5d01859a1bbb567ad93ee6) where I'm trying to set the variable `project_path` via embedded script.

I'm doing this because there is one (and in the future more) things that I want to run depending on the selected option.

That said in my log I get the following error
`2021-04-26 09:29:09: 🟡Value for variable project_path not provided, removing`

**Comment by ttscoff** [comment]
I'll have to look into this when I have some time. I don't think global frontmatter keys currently get set by snippets, but I can see how that might be useful. I'll have to look at the cascade and see where the priority should fit in (vs. variables assigned via frontmatter, url handler, script results, Bunch arguments, etc.).

**Comment by ttscoff** [comment]
BTW, just want to make sure you're clear on a couple things: Your snippet IDs (`#[police_calls]`) can have spaces, and the variable _value_ can have spaces. They're only stripped from variable names. 

Your menu could either have prettier keys, or just use an array. What you have now, with the exception of one line, is basically the equivalent of just using:

```
option = ?[
	kjaymiller
	render_engine
	bunches
	diversity
	police_calls
	ripa
	]
```

Which, if you renamed your snippet IDs, could have caps and spaces, or you could stick with the dictionary format and just give them nicer titles. You probably know all of this, just wanted to make sure based on that Bunch you linked.

**Comment by ttscoff** [comment]
So I realized I actually just don't allow variables to be set directly like that at all. I was thinking I just wasn't allowing Snippets to affect the main frontmatter keys, but I only allow assignment like that via file lines when calling a snippet or other Bunch. I can see some applications for this, at least within snippets, so I'll plan to add the capability.

**Comment by ttscoff** [comment]
Ok, added the ability to set variables directly in snippets. You can actually do it in the main Bunch, too, but it's preferable that you set those as frontmatter keys at the top to avoid confusion. Here's the question:

If a variable is set in frontmatter keys or externally (by file line, url handler, etc.), and then assigned directly in a snippet, which takes precedence? Currently (per an earlier suggestion) variables are only assigned if they're not already set (so that you can disable optional dialogs by setting a key externally). So following that logic a variable set externally or in frontmatter shouldn't be set again. But I can also see cases where you'd want to be able to assign a fallback in frontmatter, and only have it changed if certain snippets were selected. Of course, in that case you can always use a ${variable:Default Value} wherever you're using the key, so maybe it's a moot point.

**Comment by kjaymiller** [comment]
I do think that setting variables externally should override any settings but I can also see how that could would cause confusion as you would still be prompted. Is there a way that provided option could be listed as the first option in the selection?

**Comment by ttscoff** [comment]
Hierarchy is getting a bit confusing, even to me, but right now if a variable is set directly (`var = val`) in a snippet, it would prevent a `var = ?` dialog in the Bunch from showing. Which I think makes the most sense... I mean, why would you have a dialog if you were setting the variable via snippet anyway? An external variable (url, applescript, or file line when calling a Bunch/Snippet) would still override a direct assignment in a snippet.

BTW. this is going to be more valuable soon as I added basic if/else parsing[^i know] with `varname equals value` and `varname contains value` conditionals (as well as `X is running`/`X is not running` conditions. Still tweaking, and will expand available conditions over time, but this would mean that there's additional logic available based on variable assignments from any of the available options.

[^i know]: I know, I know, I said no more features until 1.4 stable release, but...

**Comment by ttscoff** [comment]
There is now full processing for variables set throughout a bunch, from frontmatter to within the bunch (using scripts, dialogs, or direct assignments) to within snippets. And variables can be changed along the way (which was important for the if/else logic). A variable set by any means will still prevent a dialog from showing, which is intentional (and I believe was your idea to begin with 😄 ), but a variable can be changed by `var =` lines at any point during processing.

I also had to change the processing order of variables and replacements to make the if/else blocks work properly. Bunch now does a better job of replacing known placeholders as it receives new variable assignments, and makes the values available in more circumstances than they were previously.
