### ISSUE TITLE
inconsistency with `from_script` generating url

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#57]
same errors with setting variables. This time around I used javascript for automation and the `from script` option to generate the following output

`option: craftdocs://createblock?parentBlockId=5FA998E8-6B9D-473D-966D-3F0DCDD34EA4&index=2000&content=https%3A%2F%2Fbunchapp.co%2Fdocs%2Fintegration%2Fadvanced-scripting%2Fcustom-dialogs.html` 

if I execute the bunch using `from script:`  I get `2021-05-07 11:13:37: :yellow_circle:Value for variable option not provided, removing
`

if I copy paste that output into the frontmatter, it works if I tell it to just run the .script `* craft_lists.applescript` it does nothing (I did remove the `option:` in that test)

**Comment by ttscoff** [comment]
Ok, so there were multiple things going on here, all of which should be fixed in the next update.

- Using `* script` to run a JXA script wasn't working because Bunch uses NSAppleScript to read any input from a `*` item, and that doesn't process JXA. The next version now falls back to executing as a shell script (using `osascript -L` from the shebang) if the script doesn't register when parsed as AppleScript. You can always just use `$ script` and let it default to the shebang. `*` is mostly for raw AppleScript commands like `* tell app "app" to do something`.
- Variables set by scripts were being erased later on in processing. Major bug on my part.
- Variables weren't being passed into snippets in some cases (especially waiting snippets) which isn't directly related to this issue but was fixed as part of handling it.
- I also found a bug in the process where the `=` in the URL was causing any line where a variable placeholder was substituted with the url to be reparsed as a variable assignment, causing a key/value pair like `craftdocs://createblock?parentBlockId: 5FA998E8-6B9D...`. Again, that wouldn't have explained this ticket's issue, but was fixed in the process.

I'm going to close this. You have the private beta now that should have all of these fixed. Please re-open if you have more to add.

**Comment by ttscoff** [comment]
Oh right, one other bug got fixed...  I wasn't allowing case insensitive matches for variable placeholders. When you assign a variable, the dictionary stores the key as lower case and with spaces compressed, so "My Var" becomes "myvar". In the case of "craftURL" it was being stored as "crafturl" and then trying to look it up as "craftURL" was failing. The beta you have is now case insensitive when looking for replacements for placeholders. In fact, it allows spaces now, giving them the same treatment, so "Craft URL" would still match "crafturl".
